## Trash note
> Note
- Hanya basic untuk fitness
- mendekati MSE

In [8]:
import numpy as np

def mean_squared_error(x, y):
  """Calculates the mean squared error between two arrays.

  Args:
    x: The first array.
    y: The second array.

  Returns:
    The mean squared error between the two arrays.
  """
  return np.mean((x - y) ** 2)

def fitness(x, y):
  """Calculates the fitness of a solution using the mean squared error.

  Args:
    x: The solution.
    y: The ground truth.

  Returns:
    The fitness of the solution.
  """
  return 1 - mean_squared_error(x, y)

# x = np.array([1, 0, 0, 1])
# y = np.array([1, 1, 1, 0])

# fitness_score = fitness(x, y)

print(fitness_score)

0.25


## MSE Completed

>Note
- Hanya tahap evaluate fitness
- Berhasil menjalankan MSE

In [53]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Create a dataset of known data points
x = np.array([1, 1, 1, 0])
y = np.array([1, 0, 1, 0])

# Reshape the x array
x = x.reshape(-1, 1)

# Train the model
model = LinearRegression()
model.fit(x, y)

# Predict the values of new data points
x_new = np.array([1, 1, 1, 1]).reshape(-1, 1)  # Reshape x_new to a 2D array
y_new = model.predict(x_new)

# Define the actual target values for the new data points
y_new_actual = np.array([1, 0, 1, 0])

# Calculate the MSE
mse = np.mean((y_new - y_new_actual) ** 2)

# Print the MSE
print(mse)

0.2777777777777778


### First test succeed

>Note: 
- Hanya mencari Evaluation fitness
- Hanya menghasilkan *Best chromosome* akhir

In [54]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Define the genetic algorithm parameters
population_size = 10
num_generations = 50
mutation_rate = 0.1

# Create a dataset of known data points
x = np.array([1, 1, 1, 0])
y = np.array([1, 0, 1, 0])

# Reshape the x array
x = x.reshape(-1, 1)

# Define the fitness function
def calculate_fitness(chromosome):
    # Train the model
    model = LinearRegression()
    model.fit(x, chromosome)

    # Predict the values of new data points
    x_new = np.array([1, 1, 1, 1]).reshape(-1, 1)  # Reshape x_new to a 2D array
    y_new = model.predict(x_new)

    # Define the actual target values for the new data points
    y_new_actual = np.array([1, 0, 1, 0])

    # Calculate the MSE
    mse = np.mean((y_new - y_new_actual) ** 2)

    # Fitness is inversely proportional to the MSE
    fitness = 1 / (mse + 1e-6)  # Add a small constant to avoid division by zero

    return fitness

# Initialize the population with random chromosomes
population = np.random.randint(0, 2, size=(population_size, len(x)))

# Main loop for the genetic algorithm
for generation in range(num_generations):
    # Calculate the fitness for each chromosome in the population
    fitness_values = np.array([calculate_fitness(chromosome) for chromosome in population])

    # Select parents based on fitness for crossover
    parents = np.random.choice(np.arange(population_size), size=population_size, p=fitness_values / np.sum(fitness_values), replace=True)

    # Create empty offspring population
    offspring = np.empty_like(population)

    # Perform crossover and mutation to create offspring
    for i in range(0, population_size, 2):
        parent1 = population[parents[i]]
        parent2 = population[parents[i+1]]

        # Perform crossover
        crossover_point = np.random.randint(1, len(x))
        offspring[i] = np.concatenate((parent1[:crossover_point], parent2[crossover_point:]))
        offspring[i+1] = np.concatenate((parent2[:crossover_point], parent1[crossover_point:]))

        # Perform mutation
        for j in range(len(x)):
            if np.random.uniform() < mutation_rate:
                offspring[i, j] = 1 - offspring[i, j]
                offspring[i+1, j] = 1 - offspring[i+1, j]

    # Replace the old population with the offspring population
    population = offspring

# Find the best chromosome after the last generation
best_chromosome = population[np.argmax(fitness_values)]

# Train the model with the best chromosome
model = LinearRegression()
model.fit(x, best_chromosome)

# Predict the values of new data points using the best model
x_new = np.array([1, 1, 1, 1]).reshape(-1, 1)  # Reshape x_new to a 2D array
y_new = model.predict(x_new)

# Define the actual target values for the new data points
y_new_actual = np.array([1, 0, 1, 0])

# Calculate the MSE
mse = np.mean((y_new - y_new_actual) ** 2)

# Print the MSE
print("Best MSE:", mse)
print("Best Chromosome:", best_chromosome)


Best MSE: 0.5
Best Chromosome: [1 1 1 1]


## Second test succeed

>Note
- 10 Generasi
- menghasilkan print untuk tiap tahap (Evaluate fitness, parent, mutation, new population)
- Terdapat *best chromosome* dan *best MSE*


In [59]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Define the genetic algorithm parameters
population_size = 10
num_generations = 10
mutation_rate = 0.1

# Create a dataset of known data points
x = np.array([1, 1, 1, 0])
y = np.array([1, 0, 1, 0])

# Reshape the x array
x = x.reshape(-1, 1)

# Define the fitness function
def calculate_fitness(chromosome):
    # Train the model
    model = LinearRegression()
    model.fit(x, chromosome)

    # Predict the values of new data points
    x_new = np.array([1, 1, 1, 1]).reshape(-1, 1)  # Reshape x_new to a 2D array
    y_new = model.predict(x_new)

    # Define the actual target values for the new data points
    y_new_actual = np.array([1, 0, 1, 0])

    # Calculate the MSE
    mse = np.mean((y_new - y_new_actual) ** 2)

    # Fitness is inversely proportional to the MSE
    fitness = 1 / (mse + 1e-6)  # Add a small constant to avoid division by zero

    return fitness

# Initialize the population with random chromosomes
population = np.random.randint(0, 2, size=(population_size, len(x)))

# Main loop for the genetic algorithm
for generation in range(num_generations):
    print(f"Generation {generation+1}:")

    # Calculate the fitness for each chromosome in the population
    fitness_values = np.array([calculate_fitness(chromosome) for chromosome in population])
    print("Fitness:", fitness_values)

    # Select parents based on fitness for crossover
    parents = np.random.choice(np.arange(population_size), size=population_size, p=fitness_values / np.sum(fitness_values), replace=True)
    print("Parents:", parents)

    # Create empty offspring population
    offspring = np.empty_like(population)

    # Perform crossover and mutation to create offspring
    for i in range(0, population_size, 2):
        parent1 = population[parents[i]]
        parent2 = population[parents[i+1]]

        # Perform crossover
        crossover_point = np.random.randint(1, len(x))
        offspring[i] = np.concatenate((parent1[:crossover_point], parent2[crossover_point:]))
        offspring[i+1] = np.concatenate((parent2[:crossover_point], parent1[crossover_point:]))

        # Perform mutation
        for j in range(len(x)):
            if np.random.uniform() < mutation_rate:
                offspring[i, j] = 1 - offspring[i, j]
                offspring[i+1, j] = 1 - offspring[i+1, j]

    # Replace the old population with the offspring population
    population = offspring

    # Print the new population
    print("New Population:")
    print(population)
    print("")

# Find the best chromosome after the last generation
best_chromosome = population[np.argmax(fitness_values)]

# Train the model with the best chromosome
model = LinearRegression()
model.fit(x, best_chromosome)

# Predict the values of new data points using the best model
x_new = np.array([1, 1, 1, 1]).reshape(-1, 1)  # Reshape x_new to a 2D array
y_new = model.predict(x_new)

# Define the actual target values for the new data points
y_new_actual = np.array([1, 0, 1, 0])

# Calculate the MSE
mse = np.mean((y_new - y_new_actual) ** 2)

# Print the best MSE and best chromosome
print("Best MSE:", mse)
print("Best Chromosome:", best_chromosome)


Generation 1:
Fitness: [1.999996   3.59998704 3.59998704 3.59998704 1.999996   1.999996
 3.59998704 3.59998704 3.59998704 3.59998704]
Parents: [1 6 5 8 2 2 2 9 9 3]
New Population:
[[0 1 0 1]
 [0 1 0 0]
 [1 1 1 1]
 [1 1 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [0 1 1 0]]

Generation 2:
Fitness: [3.59998704 3.59998704 1.999996   3.59998704 1.999996   1.999996
 3.59998704 3.59998704 3.59998704 3.59998704]
Parents: [1 6 2 1 0 6 7 0 0 8]
New Population:
[[0 1 0 0]
 [0 1 0 0]
 [0 1 1 0]
 [1 1 0 1]
 [0 1 0 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [0 1 0 1]]

Generation 3:
Fitness: [3.59998704 3.59998704 3.59998704 3.59998704 3.59998704 3.59998704
 3.59998704 3.59998704 3.59998704 3.59998704]
Parents: [6 7 7 5 8 6 8 0 0 9]
New Population:
[[0 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [1 1 0 0]
 [0 1 0 1]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 1 1]
 [0 1 1 0]]

Generation 4:
Fitness: [3.59998704 3.59998704 3.59998704 3.59998704 3.59998704 3.59998704
 3.59998704 3.59998704 3.5999

## Final Genetic Algorithm

> Notes
- Sedikit perbaikan dari sebelumnya
- menambahkan succesion rate

In [58]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Define the genetic algorithm parameters
population_size = 10
num_generations = 10
mutation_rate = 0.1

# Create a dataset of known data points
x = np.array([1, 1, 1, 0])
y = np.array([1, 0, 1, 0])

# Reshape the x array
x = x.reshape(-1, 1)

# Define the fitness function
def calculate_fitness(chromosome):
    # Train the model
    model = LinearRegression()
    model.fit(x, chromosome)

    # Predict the values of new data points
    x_new = np.array([1, 1, 1, 1]).reshape(-1, 1)  # Reshape x_new to a 2D array
    y_new = model.predict(x_new)

    # Define the actual target values for the new data points
    y_new_actual = np.array([1, 0, 1, 0])

    # Calculate the MSE
    mse = np.mean((y_new - y_new_actual) ** 2)

    # Fitness is inversely proportional to the MSE
    fitness = 1 / (mse + 1e-6)  # Add a small constant to avoid division by zero

    return fitness

# Initialize the population with random chromosomes
population = np.random.randint(0, 2, size=(population_size, len(x)))

# Main loop for the genetic algorithm
for generation in range(num_generations):
    print(f"Generation {generation+1}:")
    
    # Calculate the fitness for each chromosome in the population
    fitness_values = np.array([calculate_fitness(chromosome) for chromosome in population])
    print("Fitness:", fitness_values)
    
    # Calculate the succession rate
    succession_rate = np.sum(fitness_values) / (population_size * np.max(fitness_values))
    succession_rate_percent = succession_rate * 100
    print("Succession Rate (%):", succession_rate_percent)

    # Select parents based on fitness for crossover
    parents = np.random.choice(np.arange(population_size), size=population_size, p=fitness_values / np.sum(fitness_values), replace=True)
    print("Parents:", parents)

    # Create empty offspring population
    offspring = np.empty_like(population)

    # Perform crossover and mutation to create offspring
    for i in range(0, population_size, 2):
        parent1 = population[parents[i]]
        parent2 = population[parents[i+1]]

        # Perform crossover
        crossover_point = np.random.randint(1, len(x))
        offspring[i] = np.concatenate((parent1[:crossover_point], parent2[crossover_point:]))
        offspring[i+1] = np.concatenate((parent2[:crossover_point], parent1[crossover_point:]))

        # Perform mutation
        for j in range(len(x)):
            if np.random.uniform() < mutation_rate:
                offspring[i, j] = 1 - offspring[i, j]
                offspring[i+1, j] = 1 - offspring[i+1, j]

    # Replace the old population with the offspring population
    population = offspring

    # Print the new population
    print("New Population:")
    print(population)
    print("")

    # Calculate the succession rate
    succession_rate = np.sum(fitness_values) / (population_size * np.max(fitness_values))
    succession_rate_percent = succession_rate * 100
    print("Succession Rate (%):", succession_rate_percent)
    print("")

# Find the best chromosome after the last generation
best_chromosome = population[np.argmax(fitness_values)]

# Train the model with the best chromosome
model = LinearRegression()
model.fit(x, best_chromosome)

# Predict the values of new data points using the best model
x_new = np.array([1, 1, 1, 1]).reshape(-1, 1)  # Reshape x_new to a 2D array
y_new = model.predict(x_new)

# Define the actual target values for the new data points
y_new_actual = np.array([1, 0, 1, 0])

# Calculate the MSE
mse = np.mean((y_new - y_new_actual) ** 2)

# Print the best MSE and best chromosome
print("Best MSE:", mse)
print("Best Chromosome:", best_chromosome)


Generation 1:
Fitness: [3.59998704 1.999996   3.59998704 3.59998704 3.59998704 3.59998704
 3.59998704 3.59998704 1.999996   3.59998704]
Succession Rate (%): 91.11112888885332
Parents: [1 4 4 0 5 3 7 1 3 8]
New Population:
[[0 0 1 1]
 [0 0 0 0]
 [0 0 1 1]
 [0 1 0 1]
 [1 0 1 1]
 [1 0 1 1]
 [0 1 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [1 1 0 1]]

Succession Rate (%): 91.11112888885332

Generation 2:
Fitness: [3.59998704 1.999996   3.59998704 3.59998704 3.59998704 3.59998704
 3.59998704 1.999996   3.59998704 3.59998704]
Succession Rate (%): 91.11112888885332
Parents: [9 5 0 2 5 4 8 7 3 0]
New Population:
[[1 1 1 1]
 [1 0 0 1]
 [0 0 1 1]
 [0 0 1 1]
 [1 0 1 0]
 [1 0 1 0]
 [1 1 0 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 0 1 1]]

Succession Rate (%): 91.11112888885332

Generation 3:
Fitness: [1.999996   3.59998704 3.59998704 3.59998704 3.59998704 3.59998704
 3.59998704 3.59998704 3.59998704 3.59998704]
Succession Rate (%): 95.55556444442664
Parents: [2 7 3 8 3 4 1 8 9 1]
New Population:
[[0 0 0 0]
 [0 1 1 1]
 [0 1 0 